### PR TITLE
Rename abstract classes to emphasize that they are abstract

### PR DESCRIPTION
**Pull request by ericpoe**
We have various classes that are abstract that either show they are abstract in their name or hide that fact until one dives into the class. As such, we have 3 paradigms for abstract class names: 0) `Abstract*`; 1) `Base*`; and 2) Surprise Me!

Since the JoindIn-Web2 project has `Base*` as its manner of naming abstract classes, this PR follows suit.

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by liam-wiltshire** [comment]
Yay, conflicts :D.

@ericpoe - do you think you'll have a chance to look through this? No worries if not, I'll try to find time to do so :)

**Comment by ericpoe** [comment]
Of course there are conflicts! Two git commits enter, only one shall be victorious. @liam-wiltshire I'll take a look this evening.

**Comment by ericpoe** [comment]
@liam-wiltshire merge conflicts disappear when merging master into this branch. Woo hoo!

**Pull request merged**
