### PR TITLE
Allow event hosts to edit talks

### PR DESCRIPTION
**Pull request by ihabunek**
Hi! I believe this should work but was unable to test because the setup procedure described in `README-local-dev.md` did not work for me. :/

### CODE REVIEW

**Comment by lornajane** [comment]
It would be worth checking but the TalkMapper::thisUserHasAdminOn method _should_ handle the case where the user is an event admin.  This method is re-used in a number of places so this fix should be applied there if possible

**Comment by ihabunek** [comment]
Hm then the question would be why does this SQL code returns no rows in my case...
https://github.com/joindin/joindin-api/blob/master/src/models/TalkMapper.php#L695-L702

It's a bit hard to test since the dev setup doesn't work, and I don't have the time to debug now.

My actual issue on production is that i'm unable to edit talks for this event, and I'm the host:
https://joind.in/event/view/6049

**Comment by liam-wiltshire** [comment]
@ihabunek, @lornajane  I'm going to look into this on test. - it does look like that query should account for event admins, but likewise having read it, I'm not 100% sure if perhaps it's not correct.

Will update the test. database and have a play. however I think that if that query is incorrect, then we are probably better off fixing it in there, rather than editing a single use case?

**Comment by ihabunek** [comment]
Ok, I think I see the difference.

From `thisUserHasAdminOn`:
```sql
where rtype="event" and rcode!="pending"
```

From `thisUserHasAdminOn`:
```sql
rtype="event" and (rcode!="pending" OR rcode is null)
```
https://github.com/joindin/joindin-api/blob/master/src/models/TalkMapper.php#L700
https://github.com/joindin/joindin-api/blob/master/src/models/EventMapper.php#L515

**Comment by liam-wiltshire** [comment]
@ihabunek thanks for flagging this - I've just tested on the test platform and I get the same issue, so that does seem to be the case.

I don't have access to the VM right now so I can't check that adding `is null` is the fix, but it seems the likely candidate.

As such, are you able to back out your above change and commit with the 'new' fix, and I'll check it when I am home this evening?

Thanks!

**Comment by ihabunek** [comment]
@liam-wiltshire There, pushed the new fix. Thanks to you and @lornajane for the review.

BTW, `col != "value"` doesn't match nulls? MySQL sadness. :/

**Comment by liam-wiltshire** [comment]
One of the many joys of mySQL (!)

Thanks @ihabunek, will check it in a VM later and merge.

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by liam-wiltshire** [comment]
ok to test

**Pull request merged**
