### PR TITLE
Explain why test methods are needed

### PR DESCRIPTION
**Pull request by ericpoe**
Two of these test methods get tested, the one that is removed does not. Essentially `TestApiMapper` serves as a wrapper for `ApiMapper` and might be better served as a mock or by using reflection.

This PR explains why 2 methods in this class are needed.

### CODE REVIEW

**Comment by railto** [comment]
Ok to test

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by heiglandreas** [comment]
Wouldn't it be more interesting to actually have a test for the method instead of removing the method?

**Comment by ericpoe** [comment]
@heiglandreas I would be good with that. Shall I create an issue and close this ticket?

**Comment by heiglandreas** [comment]
Sorry for the delay, but I think closing this and adding an issue is IMHO the better option…

**Comment by railto** [comment]
I agree with @heiglandreas on this. I'm closing out this PR, please open an issue to discuss this further, thanks @ericpoe

**Pull request closed without merging**
