### PR TITLE
Show that users need to connect to legacy

### PR DESCRIPTION
**Pull request by BackEndTea**
joind.in does not have the user/oauth_allow route.
This route only exists in the legacy application

### CODE REVIEW

**Comment by lornajane** [comment]
You are correct that these docs are out of date.  However the users should be using the endpoints on the API, _not_ the legacy site which will be turned off at some future time.  There should be docs on this somewhere but if not, the current website logs users in by this route so that could be a good example to look at.

**Comment by akrabat** [comment]
The API docs are here: http://joindin.github.io/joindin-api/

**Comment by BackEndTea** [comment]
> However the users should be using the endpoints on the API, not the legacy site which will be turned off at some future time.

The login through the current website ends up in this function if I'm correct.
https://github.com/joindin/joindin-api/blob/56baaac6e6969b15c9be60b0c8a2266485dc2271/src/controllers/TokenController.php#L9

That requires me to send along a username and password, instead of allowing the user to enter it there themselves.

**Comment by lornajane** [comment]
These docs might be more help http://joindin.github.io/joindin-api/howto/authenticate.html - the website uses a different style of OAuth grant because it's a trusted client.  We might be more help if we knew what it was you wanted to do, feel free to share a bit more information about your project if you would like to?

**Comment by lornajane** [comment]
Oh I love this idea!  We had something like this a while ago but it hasn't been active lately https://github.com/joindin/JoindIn.js

**Comment by BackEndTea** [comment]
Of course, I just meant that the mentioned javascript library does not have that functionality.

**Comment by akrabat** [comment]
Ah! Sorry. I misread.

**Pull request closed without merging**
