### PR TITLE
Added talk_link_types table

### PR DESCRIPTION
**Pull request by toby-griffiths**
As requested by Rob

### CODE REVIEW

**Comment by lornajane** [comment]
add to whitelist

**Comment by akrabat** [comment]
bah! Can't type a number. Sorry.

**Comment by lucianoqueiroz** [comment]
Do we need some seed for this table? What types of link will be available?

**Comment by heiglandreas** [comment]
I'd at least seed it with 'slides' and perhaps 'video' would be another option. Further suggestions?

**Comment by lucianoqueiroz** [comment]
We already have the "slides_link" column on talks table. The description on Jira says: _Often talks have items in addition to slides - maybe a zip file of code examples or a podcast or a video or something - the ability to add additional links to the talk with this information would be great.
_

**Comment by lucianoqueiroz** [comment]
I think we can have: Video, Code Examples, Podcast, Text ?

**Comment by heiglandreas** [comment]
Will we put the slides in there as well? Or shall they remain in the talk-table? I'd move them over as well. So there would then also be 'Slides'

**Comment by akrabat** [comment]
> Will we put the slides in there as well? Or shall they remain in the talk-table? I'd move them over as well. So there would then also be 'Slides'

Legacy uses the slides column in that table. I seem to remember discussion that we'd put slides in the new table, and automatically sync to the column in the talks table.

**Comment by akrabat** [comment]
Found it!

See https://joindin.jira.com/browse/JOINDIN-650 & https://joindin.jira.com/browse/JOINDIN-651

**Comment by lucianoqueiroz** [comment]
> The old website expects a slides_link field in the talks table. We now store this information in the new talk_links table, but we need to manage the migration here.
> When a talk_link is created, add the URL to the talks table if there is not already a URL there.
> When a talk_link is edited and the URL changes, check if the same URL was stored in the talk.slides_link column and if so, update that also.
> When a talk_link is deleted, if its URL is used in the talks table, empty that field. If there are other valid talk_links for this talk, add one to the talks table.

As we will have multiple links per talk, what if the user first adds other link rather than "slides"? The label on legacy site expects a slide url...

**Comment by akrabat** [comment]
This conversation should be held on the relevant JIRA ticket as it will be lost here.

**Pull request merged**
