### PR TITLE
Add Constructor to ApiView classes

### PR DESCRIPTION
**Pull request by ericpoe**
A constructor in this case shows a relationship between the various ApiView classes. This also shows that JsonPView has an added requirement in its constructor.

`JsonView` has an implied property made explicit. I could have put this in a constructor, but it didn't make sense to take that extra step.

### CODE REVIEW

**Comment by railto** [comment]
ok to test

**Comment by heiglandreas** [comment]
Looks good to me! I'D merge that. 

Thanks @ericpoe for the work!

**Comment by ericpoe** [comment]
I'll look into these merge conflicts this evening @heiglandreas

**Comment by ericpoe** [comment]
@heiglandreas Merge conflict resolved

**Pull request merged**
