### PR TITLE
JOINDIN-600: Comment poster should not get comment notification

### PR DESCRIPTION
**Pull request by bcremer**

### CODE REVIEW

**Comment by phoenixrises** [comment]
Is the additional function really required?

**Comment by bcremer** [comment]
@phoenixrises it's not required but it's private and in my opinion it makes the intent of the condition clearer.

**Comment by phoenixrises** [comment]
But you could say that for just about any condition ever couldn't you? Personally a comment would have done imo, but will leave it up to the reviewers, either way, at least it's done :)

**Comment by akrabat** [comment]
ok to test

**Comment by akrabat** [comment]
This requires more work as there's no guarantee that `$person` will have a `user_id` column (unclaimed speakers).

I'm closing for now. Feel free to reopen when addressed.

**Pull request closed without merging**
