### PR TITLE
Enhancement: Add Travis CI build status badge to README.md

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a Travis CI build status badge to `README.md`

### CODE REVIEW

**Comment by svpernova09** [comment]
Do we need this if we take #714? (Which I plan on accepting as soon as we get good builds)

**Comment by localheinz** [comment]
@svpernova09 

As long as we don't have it yet, it's useful!

**Comment by svpernova09** [comment]
You're not wrong :D

**Comment by localheinz** [comment]
Thank you, @svpernova09!

**Pull request merged**
