### PR TITLE
Adapt tests to work with PHPUnit > 5

### PR DESCRIPTION
**Pull request by heiglandreas**

### CODE REVIEW

**Comment by exussum12** [comment]
Clearly not for this ticket but vendor should be removed at some point, Makes this look much bigger than it really is

**Comment by heiglandreas** [comment]
I'm absolutely with you on that! Doing the deployment right with composer would make the whole codebase much smaller ;-)

One step at a time…

**Comment by railto** [comment]
Had a chat with @heiglandreas and we've both agreed that this should be put on ice until #446 is taken care of

**Comment by ericpoe** [comment]
Let's revisit after #446 is merged in.

**Comment by heiglandreas** [comment]
Rebased onto the current master...

**Pull request merged**
