### PR TITLE
Database performance improvements (indexes, query simplification)

### PR DESCRIPTION
**Pull request by fatalmind**
Some suggestios to improve performane #DPC19

### CODE REVIEW

**Comment by iansltx** [comment]
@fatalmind You may want to base this branch on the one mentioned in https://github.com/joindin/joindin-api/pull/674, as I was working on something similar elsewhere earlier. You'll also need to bump the patch count so ours can both land without conflicting.

**Comment by iansltx** [comment]
Also, given that get_talk_rating() is used 2x in the entire codebase, what do you think about replacing it with a view? Writing up the query that would result in that view now.

**Comment by iansltx** [comment]
Something like this:

```
select round(avg(rating)), tc.talk_id
from talk_comments tc
left join talk_speaker ts on ts.talk_id = tc.talk_id
where tc.user_id != 0 && (ts.speaker_id IS NULL || tc.user_id != ts.speaker_id) &&
tc.rating != 0 && tc.private = FALSE && tc.active = TRUE
GROUP BY tc.talk_id;
```

**Comment by iansltx** [comment]
Seems like your idx_talk_priv_act works nicely with that view too.

**Comment by iansltx** [comment]
If you're up for the view changes, that'd be amazing. If not, this looks fine as-is, and I'll add a follow-on issue to deal with this function.

**Comment by heiglandreas** [comment]
Obsoleted by #681

**Pull request closed without merging**
