### PR TITLE
Fix legacy slides

### PR DESCRIPTION
**Pull request by exussum12**

### CODE REVIEW

**Comment by exussum12** [comment]
The issue is the slides link does not appear on the search page. 

It's not maintained but the API should still accept it

**Comment by railto** [comment]
@exussum12 Sorry for the delay in getting back you. Happy to merge this in, however before I do, phpcs has picked up an error in the change, could you please update the code to correct this? Thanks

```
<checkstyle version="2.3.4">
<file name="/vagrant/joindin-api/src/controllers/TalksController.php">
 <error line="361" column="9" severity="error" message="Expected 1 space after IF keyword; 0 found" source="Squiz.ControlStructures.ControlSignature.SpaceAfterKeyword"/>
</file>
</checkstyle>
```

**Comment by exussum12** [comment]
Fixed that, Shocked that I missed it :scream:

**Comment by railto** [comment]
No worries, happens to us all sometimes, thanks for the PR

**Pull request merged**
