### PR TITLE
Enhancement: Add basic configuration for Dependabot

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a configuration for [Dependabot](https://dependabot.com)

💁‍♂ Now it would only need to be enabled for this repository!

### CODE REVIEW

**Comment by svpernova09** [comment]
Thoughts on this @joindin/leadership-team?

**Comment by mwillbanks** [comment]
Personally, I really like this.  I think the `version_requirement_updates` is good for right now (`increase_versions`), however, I do think it would be good to eventually get it to `widen_ranges` so that we move forward with larger version increases but that is easier when there is a develop branch.

Further, we should look at the `allowed_updates` configuration option a bit deeper; in the more general case the master branch is set for `security` only while the develop branch contains all dependencies.

Either way, it looks good to me!

**Comment by localheinz** [comment]
Thank you, @mcneely, @mwillbanks, and @svpernova09!

**Comment by localheinz** [comment]
@mcneely @svpernova09 

Has an integration been set up yet?

**Comment by localheinz** [comment]
Sounds good, @svpernova09!

**Pull request merged**
