### PR TITLE
Add link to talk claim acceptance email

### LINKED ISSUE #444: Add link to talk in claim confirmation email
I just received a talk claim confirmation email, and I noticed that no link to the talk was in it... Maybe we should add it?

### PR DESCRIPTION
**Pull request by mattstauffer**
Apologies ahead of time: I have not tested this!

I downloaded the code and grepped around and updated it quickly before the end of a conference I'm at.

If no one has eyes for it right now, I'll try to get the whole database running locally when I'm home from this conference and test it out.. but I figured I'd throw this up and see if it's an easy merge or easy for someone else to test.

Also, blame @liam-wiltshire :)

image

<3

Closes #444

### CODE REVIEW

**Comment by railto** [comment]
Thanks @mattstauffer, I'm planning on spending some time tonight going through the open backlog and will take a look at this.

**Comment by railto** [comment]
Thanks for the PR @mattstauffer.  I've looked it over and given it a test and all seems fine, one slight thing however.  Would you mind updating the MD file so that the URI comes in as a link, at present it just renders as text.

Once that's done then we can get it merged straight in.

Thanks again

**Comment by mattstauffer** [comment]
@railto thanks for testing it out! I *think* I got the right syntax for linking it? Apologies I didn't do that at first, I just assumed it was going to auto-link. 

Thanks!

**Comment by railto** [comment]
Thanks @mattstauffer, works a treat.  Thanks again for the PR, really appreciate it.

**Comment by mattstauffer** [comment]
<3 Thanks @railto !

**Pull request merged**
