### PR TITLE
Fix: Require PHP 7.2

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires PHP 7.2
* [x] adds PHP 7.2 to the Travis CI build matrix

### CODE REVIEW

**Comment by localheinz** [comment]
@zghosts 

See [`composer.json`](https://github.com/joindin/joindin-api/blob/eed4bc040dd290daa562cdb140eed2a9c4d20a1a/composer.json#L34-L36):

https://github.com/joindin/joindin-api/blob/eed4bc040dd290daa562cdb140eed2a9c4d20a1a/composer.json#L34-L36

**Comment by localheinz** [comment]
@zghosts 

In other words, as the required PHP version is currently not documented in `composer.json`, and we currently run builds on Travis CI against PHP 7.3, what should be the required (and supported) minimum version of PHP?

**Comment by iansltx** [comment]
Thinking we hold off on the 7.3 explicit bump until Ubuntu 19.10 gets released later this month. We've been running it in prod since the switchover early this year FWIW.

**Comment by localheinz** [comment]
@iansltx 

Shall we use PHP 7.2, then, or PHP 7.1?

**Comment by iansltx** [comment]
As I recall, we have deps that need 7.2 already. No need to drop to 7.1.

**Comment by localheinz** [comment]
@iansltx @zghosts 

Updated!

**Comment by svpernova09** [comment]
Thanks :D

**Comment by zghosts** [comment]
Thanks!

**Comment by localheinz** [comment]
Thank you, @iansltx, @svpernova09, and @zghosts!

**Pull request merged**
