### PR TITLE
Removes CfPs that have not yet started

### PR DESCRIPTION
**Pull request by heiglandreas**
Currently CfPs that have not yet started will be shown in the CfP-list. This PR fixes that by removing CfPs with start-date greater than the current date from the list. That's the same behaviour as removing CfPs that are already closed from the CfP-List

### CODE REVIEW

**Comment by dstockto** [comment]
It seems it might be valuable to know what CfPs are about to start.

**Comment by heiglandreas** [comment]
It might happen (and already happened) that an event was added to joind.in that had a CfP start in 2 months time. So that CfP will be shown for 2 months without it being open. And as the Web-Interface didn't show the beginning or the end of a CfP in the CfP sidebar or on the CfP-Page I would assume as a user that those CfPs are already open.

That was the reason why I removed the CfPs that had not yet started from that list.

If we decide otherwise I'm fine (but will have to adapt callingallpapers accordingly :wink: )

**Comment by akrabat** [comment]
Maybe show those that will start within the next 7 days?

**Comment by heiglandreas** [comment]
No problem. I'll fix that ASAP

**Comment by heiglandreas** [comment]
I've just seen that in the API the key to the CfPs is labeled "open-cfps". (http://api.joind.in) - So should we reconsider? I've just implemented the "7 days in advance".

**Comment by lornajane** [comment]
Looks good to me, thanks Andreas :)

**Pull request merged**
