### PR TITLE
Running phpcbf not all errors are fixable though

### PR DESCRIPTION
**Pull request by exussum12**
Fair few errors left. non auto fixable though.

Need to namespace is the biggest one

### CODE REVIEW

**Comment by liam-wiltshire** [comment]
ok to test

**Comment by liam-wiltshire** [comment]
@exussum12 Not sure what I've merged that is causing this to conflict, however could you please take a look at re-basing this for me please?

Thanks for all your recent efforts :)

**Comment by exussum12** [comment]
Yeah no problem. Will take a look at this again. It changes a large amount of files to be fair.

**Comment by exussum12** [comment]
Fixed

phpcs --standard=psr2 --encoding=php tests
phpcs --standard=psr2 --encoding=php src

To test it (and running the main unit tests)

**Pull request merged**
