### PR TITLE
Replace the speaker_name when a talk claim is approved

### PR DESCRIPTION
**Pull request by liam-wiltshire**
Fixes https://joindin.jira.com/browse/JOINDIN-745

### CODE REVIEW

**Comment by heiglandreas** [comment]
While this fixes https://joindin.jira.com/browse/JOINDIN-745 it does not fix https://joindin.jira.com/browse/JOINDIN-742 though the reasons are similar…

Wouldn't a more generic approach be more interesting? Like setting the user-name in the edit-field of approved talks from the speakers name and not from the name field?

**Comment by liam-wiltshire** [comment]
Yes, I agree in principle, but we needed a quick fix as speakers were losing claimed talks - affected 5 speakers at tek for example.

**Comment by heiglandreas** [comment]
No Problem at all! I'm already working on a more general fix…

**Comment by heiglandreas** [comment]
Find a generic fix in PR #413

**Pull request merged**
