### PR TITLE
JOINDIN-580 - Provide an edit point for list of languages

### PR DESCRIPTION
**Pull request by mikegsmith76**
Hi,

I believe this should meet the requirements for the ticket above. However if any additional changes are required please let me know

Thanks
Mike

### CODE REVIEW

**Comment by akrabat** [comment]
Out of interest, why did you close this?

**Comment by mikegsmith76** [comment]
i wasn't sure if the pull request was required, and when checking over the weekend github reported there were now merge conflicts between this and presumably other changes that have been made since this change was made. i'm happy to reopen if i'm mistaken?

**Comment by akrabat** [comment]
I've reopened. We can be really slow at merging things into the project as we're all really busy with real-life things. Sorry.

Don't worry too much about the merge conflicts as I can rebase when I merge and will comment if I have any questions.

**Comment by akrabat** [comment]
ok to test

**Comment by mikegsmith76** [comment]
No apology necessary, if any updates are required please let me know

**Comment by lornajane** [comment]
Thanks Mike!  I refactored a little bit because we're changing the way we do routing/controllers but otherwise it looked great and it's in now :)

**Comment by mikegsmith76** [comment]
Thanks Lorna!

**Pull request merged**
