### PR TITLE
Add Travis checks

### PR DESCRIPTION
**Pull request by exussum12**
Currently only doing psr2 and phpunit

### CODE REVIEW

**Comment by exussum12** [comment]
This will need someone to enable travis on the build. https://docs.travis-ci.com/user/getting-started/

First few steps of that

**Comment by heiglandreas** [comment]
Currently we are using jenkins for the CI-pipeline at http://jenkins.joind.in

So far we did not (yet) decide to move away from that.

Though there are some ideas to change the projects setup there is no decission to actually change all that. We should schedule a chat session on IRC to discuss that stuff.

But as long as there is no decission to move CI from jenkins to github I would not invest time into such a move. 
B

**Comment by exussum12** [comment]
Jenkins doesn't currently work (hence the reason for the psr2 pull request as it was already done) 

Some talk about it here 


https://github.com/joindin/joindin-api/pull/447#issuecomment-396944443

Personally I would prefer travis as it shows correctly on the commits

**Comment by heiglandreas** [comment]
Personally I'm also :+1: on that. I would just prefer a team decission on the future strategy and vision of the whole project so that we can then actually move on strongly in one direction.

**Comment by exussum12** [comment]
Happy be in involved in a chat. When's best to set one up ?

**Comment by railto** [comment]
Moving away from Jenkins is part of a larger conversation around the infrastructure behind joindin. There are things being done in Jenkins that need to be looked into to see if they can be easily replicated in Travis or another service like CircleCI.

This is something that I'm personally going to be looking into over the coming weeks and once I have a solid grasp on what currently happens vs what needs to be done then I'd like to get a conversation going around this.

@exussum12 Thank's for submitting the PR.  I'm going to close it for now, but we may well end up using it in future, however, for now, I'd rather stick with Jenkins until we figure out the bigger picture

**Comment by exussum12** [comment]
Nothing is done currently in Jenkins though due to it being broke for almost a year ?

What is here currently set up travis and then runs a shell script, that can be done easily for any provider we use. To me having something working is better than not having anything even if its just temporary ?

**Comment by railto** [comment]
Per IRC discussion, re-opening this. Would love to see the same for Web2

**Pull request merged**
