### PR TITLE
Removes Timezone-class

### PR DESCRIPTION
**Pull request by heiglandreas**
This commit removes the Timezone-class that was used at two locations by altering those two locations to a more recent approach by adding calls to the DateTime-family directly in the code.

This also removes the test-file.

### CODE REVIEW

**Comment by heiglandreas** [comment]
There you go ;)

**Comment by liam-wiltshire** [comment]
Thanks, will give it a once-over and merge this evening.

**Comment by liam-wiltshire** [comment]
@heiglandreas - I've tried this locally and it doesn't seem to work.

If I checkout the master branch, http://api.dev.joind.in/v2.1/events returns events as normal, however if I checkout your branch, I get:

0: DateTime::__construct(): Failed to parse time string (1536695254) at position 8 (5): Unexpected character

Does this not happen on your local?

Liam

**Comment by heiglandreas** [comment]
Thanks for noting. I have no Idea *what* I tested during creation but it seemed not to be the change i introduced here.... 

Fixed the issue though!

**Comment by liam-wiltshire** [comment]
This seems ok now, thanks.

**Pull request merged**
