### PR TITLE
Fix path for event icons

### PR DESCRIPTION
**Pull request by Jean85**
As in title. Discovered this with @akrabat in IRC..

### CODE REVIEW

**Comment by akrabat** [comment]
ok to test

**Comment by Jean85** [comment]
This isn't testable without https://github.com/joindin/joindin-vm/pull/89
Without that you can't upload anything locally. Also, I think this needs some further work, because after a successful upload the link given by the API seems wrong. 

Right now I get `https://joind.in/inc/img/event_icons/icon-4-small.jpg` which is wrong multiple times:
 * no `dev.` in base URL
 * even using `dev.` manually, I get a `Refused connection` error (maybe Apache is misconfigured?)

**Comment by Jean85** [comment]
Ok now it seems to work, tested locally.

**Comment by liam-wiltshire** [comment]
Seems to work for me too

**Comment by Jean85** [comment]
Can we merge this then?

**Comment by heiglandreas** [comment]
It's not critical in that it will bring the live-servers down as it's the fallback for local installations. You tested it localy and it worked. @liam-wiltshire Tested it as well. So **I'd** merge it!

**Pull request merged**
