### PR TITLE
Hide the first ratings

### PR DESCRIPTION
**Pull request by heiglandreas**
Often it looks like the rating and the tone of the first comment influence the following ratings and comments. To allow people to rate and comment without being influenced too much this PR hides the comments until a certain threshold has been reached. Currently that is either more than 3 comments or the talk has been given more than 3 days ago. Until one of these thresholds has been reached there are no comments shown for the talk. 

Hopefully that will allow a more uninfluenced rating of talks…

### CODE REVIEW

**Comment by railto** [comment]
Unfortunately getting a couple of errors on PHPCS for this PR:

```
<checkstyle version="2.3.4">
<file name="/vagrant/joindin-api/src/models/TalkModelCollection.php">
 <error line="80" column="1" severity="error" message="The closing brace for the class must go on the next line after the body" source="PSR2.Classes.ClassDeclaration.CloseBraceAfterBody"/>
</file>
<file name="/vagrant/joindin-api/src/models/TalkCommentMapper.php">
 <error line="219" column="18" severity="warning" message="Line exceeds 120 characters; contains 124 characters" source="Generic.Files.LineLength.TooLong"/>
</file>
</checkstyle>
```

Also getting phpunit errors which seem to be similar to what was seen in #445 and may also need to wait on #446 being completed

```
[exec] PHP Warning:  require_once(/vagrant/joindin-api/vendor/composer/autoload_static.php): failed to open stream: No such file or directory in /vagrant/joindin-api/vendor/composer/autoload_real.php on line 28
     [exec] PHP Stack trace:
     [exec] PHP   1. {main}() /usr/local/bin/phpunit:0
     [exec] PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:520
     [exec] PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:109
     [exec] PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:120
     [exec] PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:633
     [exec] PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:804
     [exec] PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
     [exec] PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
     [exec] PHP   9. require_once() /vagrant/joindin-api/tests/bootstrap.php:3
     [exec] PHP  10. include() /vagrant/joindin-api/src/inc/Autoloader.php:15
     [exec] PHP  11. ComposerAutoloaderInitbe312af39897752bf33b8dfb0cb5182c::getLoader() /vagrant/joindin-api/vendor/autoload.php:7
     [exec]
     [exec] Warning: require_once(/vagrant/joindin-api/vendor/composer/autoload_static.php): failed to open stream: No such file or directory in /vagrant/joindin-api/vendor/composer/autoload_real.php on line 28
     [exec]
     [exec] Call Stack:
     [exec]     0.0007     386240   1. {main}() /usr/local/bin/phpunit:0
     [exec]     0.0619   11826080   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:520
     [exec]     0.0619   11826704   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:109
     [exec]     0.0619   11829608   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:120
     [exec]     0.0668   11851480   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:633
     [exec]     0.0668   11851544   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:804
     [exec]     0.0676   11851712   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
     [exec]     0.0685   11872656   8. include_once('/vagrant/joindin-api/tests/bootstrap.php') phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
     [exec]     0.0712   11885920   9. require_once('/vagrant/joindin-api/src/inc/Autoloader.php') /vagrant/joindin-api/tests/bootstrap.php:3
     [exec]     0.0725   11887856  10. include('/vagrant/joindin-api/vendor/autoload.php') /vagrant/joindin-api/src/inc/Autoloader.php:15
     [exec]     0.0747   11907304  11. ComposerAutoloaderInitbe312af39897752bf33b8dfb0cb5182c::getLoader() /vagrant/joindin-api/vendor/autoload.php:7
     [exec]
     [exec] PHP Fatal error:  require_once(): Failed opening required '/vagrant/joindin-api/vendor/composer/autoload_static.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/joindin-api/vendor/composer/autoload_real.php on line 28
     [exec] PHP Stack trace:
     [exec] PHP   1. {main}() /usr/local/bin/phpunit:0
     [exec] PHP   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:520
     [exec] PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:109
     [exec] PHP   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:120
     [exec] PHP   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:633
     [exec] PHP   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:804
     [exec] PHP   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
     [exec] PHP   8. include_once() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
     [exec] PHP   9. require_once() /vagrant/joindin-api/tests/bootstrap.php:3
     [exec] PHP  10. include() /vagrant/joindin-api/src/inc/Autoloader.php:15
     [exec] PHP  11. ComposerAutoloaderInitbe312af39897752bf33b8dfb0cb5182c::getLoader() /vagrant/joindin-api/vendor/autoload.php:7
     [exec]
     [exec] Fatal error: require_once(): Failed opening required '/vagrant/joindin-api/vendor/composer/autoload_static.php' (include_path='.:/usr/share/php:/usr/share/pear') in /vagrant/joindin-api/vendor/composer/autoload_real.php on line 28
     [exec]
     [exec] Call Stack:
     [exec]     0.0007     386240   1. {main}() /usr/local/bin/phpunit:0
     [exec]     0.0619   11826080   2. PHPUnit_TextUI_Command::main() /usr/local/bin/phpunit:520
     [exec]     0.0619   11826704   3. PHPUnit_TextUI_Command->run() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:109
     [exec]     0.0619   11829608   4. PHPUnit_TextUI_Command->handleArguments() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:120
     [exec]     0.0668   11851480   5. PHPUnit_TextUI_Command->handleBootstrap() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:633
     [exec]     0.0668   11851544   6. PHPUnit_Util_Fileloader::checkAndLoad() phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php:804
     [exec]     0.0676   11851712   7. PHPUnit_Util_Fileloader::load() phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:38
     [exec]     0.0685   11872656   8. include_once('/vagrant/joindin-api/tests/bootstrap.php') phar:///usr/local/bin/phpunit/phpunit/Util/Fileloader.php:56
     [exec]     0.0712   11885920   9. require_once('/vagrant/joindin-api/src/inc/Autoloader.php') /vagrant/joindin-api/tests/bootstrap.php:3
     [exec]     0.0725   11887856  10. include('/vagrant/joindin-api/vendor/autoload.php') /vagrant/joindin-api/src/inc/Autoloader.php:15
     [exec]     0.0747   11907304  11. ComposerAutoloaderInitbe312af39897752bf33b8dfb0cb5182c::getLoader() /vagrant/joindin-api/vendor/autoload.php:7
     [exec]

BUILD FAILED
/vagrant/joindin-api/build.xml:21:38: Task exited with code 255
Total time: 0.2193 seconds
```

**Comment by heiglandreas** [comment]
retest this please

**Comment by exussum12** [comment]
May need @liam-wiltshire  / @lornajane to set up but can the qa tools run when a PR has been made ? happy to help with travis files if needed

**Comment by heiglandreas** [comment]
@exussum12 the QA tools did run up until last december with every push. Something broke then and we're actually trying to figure out what it is that hinders jenkins from doing what he should do… 😉

**Comment by heiglandreas** [comment]
build

**Comment by lornajane** [comment]
@exussum12 I think Travis integration would be a huge win for this project if you're up for it! We're 10 years old this year and Travis wasn't invented then... Do you want to open a WIP pull request and add me? I'd be happy to share any knowledge I have and to review this, set up whatever config we need, etc

**Comment by lornajane** [comment]
Also, sorry @heiglandreas but I'm :-1: on this feature now I'm looking at where this conversation started. We've always been about immediate and open feedback. It's not my call though.

**Comment by Pton** [comment]
Maybe you could show the amount of reviews instead of hiding the reviews until a threshold is reached? That way users themselves can judge if they agree with the tone set by the first (few) reviews.

**Comment by railto** [comment]
Thanks for submitting this @heiglandreas 

I've discussed this with @liam-wiltshire and we are both in agreement with @lornajane's original thoughts, this is not something that we want to do. Joindin is about providing quick and open feedback and I feel that this will actually harm the project more than it helps.

**Pull request closed without merging**
