### PR TITLE
Fixes issue with creating a talk.

### PR DESCRIPTION
**Pull request by railto**
Insert query had slides_link as field, but no value set for it.

### CODE REVIEW

**Comment by exussum12** [comment]
Also I think I added tests around here. Any chance of a test adding

**Comment by railto** [comment]
This fixes a bug that was introduced in https://github.com/joindin/joindin-api/pull/440/files, the value etc for slides_link was removed but the field not.

**Comment by heiglandreas** [comment]
That probably would not have shown up in a unit-test. And the integration-test-suite is not really in a healthy state... :-/

**Comment by exussum12** [comment]
Ah i see. I already handled the legacy slide media. I will experiment with dropping that column I don't think we will need it any more. 

Thanks for fixing @railto

**Pull request merged**
