### PR TITLE
WIP: Allow retrieval of reported comments

### PR DESCRIPTION
**Pull request by elstamey**
- [x] set up the routes
- [ ] create test data
- [ ] write tests
- [ ] protect these endpoints, restrict to event and site admins

### CODE REVIEW

**Comment by elstamey** [comment]
This is NOT ready to review.  I'm about to commit work in progress in order to receive some feedback.

**Comment by akrabat** [comment]
ok to test

**Comment by akrabat** [comment]
Looks fine so far

**Comment by lornajane** [comment]
PR https://github.com/joindin/joindin-api/pull/297 builds on this one, so closing this in favour of it

**Pull request closed without merging**
